version: '3.4'

# "docker-compose up" sets up a default network
# its container has its own virtual NIC
# each virtual NIC connects to the OS's virtual switch (on Windows, it's Hyper-V virtual switch)
# and Hyper-V virtual switch connects to the host's NIC!!! (NOTE THAT network is a web where NICs connect to each other using wires!!!!)
# Since containers are sealed, no way to inject service-ip entries to their DNS cache or host files, I guess docker-compose's network has its own local DNS name server to accept DNS queries from containers!!
services:
  app1:
    build: ./webapp 
    container_name: app1
    command: 9001 "Server 1"
    # the first port is the host's port ===> we can access this service using "http://localhost:9001"
    ports: 
      - "9001:9001"

  app2:
    build: ./webapp
    container_name: app2
    command: 9002 "Server 2"
    ports: 
      - "9002:9002"

  app3:
    build: ./webapp
    container_name: app3
    command: 9003 "Server 3"
    ports: 
      - "9003:9003"

  haproxy:
    build: ./haproxy
    container_name: haproxy
    # we can access this service using "http://localhost:80" and "http://localhost:83"
    ports:
      - "80:80"
      - "83:83"

  